### PR TITLE
Initial pass at set_border functionality

### PR DESCRIPTION
**Pull request by RARowe**
Hello!

Feel free to reject right away, but I was hoping to get feedback on the "set border" functionality that I, _hopefully_, finished up.

I looked through some of the notes in the TODO that were there, and tried to follow it to the best of my ability.

I also realize there is an "expanded tab" in here, which will need to be fixed, but I am not by my primary computer, so I can't make that fix right now.

**Tested**:
-Linux: Yes, Raspbian (would like you to try it to see if you think it's what you're looking for, cause I don't know your configuration, and I'm possibly not considering some things)
-BSD: No

**Biggest changes:**
- `window/set-border!` now only has two required arguments, the `s_wid` and the `s_width`
- `s_color` is now a true optional argument
- The `width` and `color` C-values were getting turned into signed integers, and are now unsigned
    - This allowed me to remove the checks for negative
    - I couldn't find great xcb docs on whether they should be signed or not, but other examples make me think this is correct, and, in the context of "width" and "color", the idea of a "negative" value does not exist
- I left the `retVal` the same. I don't know what would be a better thing to return. Maybe windowId *shrug*

Thank you!

### CODE REVIEW

**Comment by luizdemilon** [comment]
Looks great to me! I'll test this today. Thank you so much!

**Comment by RARowe** [comment]
Great! Thanks so much!

If you have any questions, or need any changes, let me know!

**Comment by RARowe** [comment]
Really like the project by the way!

I saw you remark somewhere that you may switch to using the guile xcb library to build a WM. Are you still considering that, or are you just going to work on this one?

**Comment by luizdemilon** [comment]
Thanks for the pull request!



> Really like the project by the way!
> 
> I saw you remark somewhere that you may switch to using the guile xcb library to build a WM. Are you still considering that, or are you just going to work on this one?

I'd like to, but I kinda bit off too much. I think I'm going to keep the C version for now.

**Comment by RARowe** [comment]
Any TODOs you really want?
I like the idea of daemonizing Xlambda.
I also have some ideas about how to handle keyboard callbacks... I've done some research from the Bspwm codebase, and looked into how to handle it for Guile. I would use libuv, as is mentioned in your README, or I could give an initial pass with a simple pthread implementation.

**Comment by luizdemilon** [comment]
Guile has REPL servers, so ideally you'd be able to connect.

I was recommended libuv, but im not sure what's best for async, C-wise.

Thanks for offering help by the way! I think that's just what Xlambda needs to get off the ground again! :D

**Comment by luizdemilon** [comment]
Ideally, the main TODO is really getting Xlambda usable standalone.

The rest will probably come easier, after that

**Pull request merged**
